### ISSUE TITLE
[BUG] Plugin fails on startup

### ISSUE THREAD

**Issue by ctron** [Renaud11232/OctoPrint-Resource-Monitor#31]
**Describe the bug**

The plugin doesn't start and fails to show in the UI.

**To Reproduce**

1. Install

**Expected behavior**

It shows its UI.

**Screenshots**

Nothing to show

**Version of OctoPrint-Resource-Monitor**

0.3.2

**Server configuration**
 - OS: OctoPi
 - Browser: Firefox, Chrome, Edge
 - Python version 3.x

**OctoPrint logs with `octoprint.plugins.resource_monitor` set to DEBUG**

~~~
2021-04-05 21:33:29,138 - octoprint.server.views - ERROR - Error while retrieving template data for plugin resource_monitor, ignoring it
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/views.py", line 1188, in fetch_template_data
    vars = implementation.get_template_vars()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_resource_monitor/__init__.py", line 65, in get_template_vars
    partitions=self.__monitor.get_partitions(all=False),
AttributeError: 'ResourceMonitorPlugin' object has no attribute '_ResourceMonitorPlugin__monitor'
~~~

**Browser console logs**

Upload the logs of your browser here, on Chrome press F12 and go in the console tab

**Comment by Renaud11232** [comment]
Hello,

Thanks for the report, I think I have an idea of what the issue is. Just to be sure, could you send me the full logs ? You can directly upload the file on github or copy paste it in an answer.

Thanks
